---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/downloads/sonarr
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/bjw-s/helm
      chart: app-template
      targetRevision: 3.7.3
      helm:
        releaseName: sonarr
        valueFiles:
          - $repo/kubernetes/apps/downloads/sonarr/values.yaml
  destination:
    name: in-cluster
    namespace: downloads
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
