---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: external-secrets
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/kube-system/external-secrets/chart
      targetRevision: main
      ref: repo
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.17.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $repo/kubernetes/apps/kube-system/external-secrets/chart/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
