---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: igpu
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/kube-system/igpu
      targetRevision: main
      ref: repo
    - repoURL: https://intel.github.io/helm-charts/
      chart: intel-device-plugins-gpu
      targetRevision: 0.32.1
      helm:
        releaseName: igpu
        valueFiles:
          - $repo/kubernetes/apps/kube-system/igpu/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
