---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kubernetes-secret-generator
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - chart: kubernetes-secret-generator
      repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      targetRevision: 0.17.3
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
