apiVersion: v1
kind: Secret
metadata:
  name: coroot-admin
  namespace: coroot
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:CnzXQ3+3V6OQ4wcnRRYMBZk5K8byTQKBk6xt45oivpSL9qdT9C39q981nA==,iv:XUkgu20GuHcOTBtvwZmwPSkE1VmG0nzo/qDnrxalLnk=,tag:gTmqDDYZ37MjXOUjD6rgvw==,type:str]
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV3JmRHhzckVUSDJJSzB2
        U3dsQmJZNm96cURwZHpQUjZrWE50WkltZ1FrCkEycitUOUhWeDFwU0lyT1BGZDA3
        RW0xTmJrYVQrczBqbWUyZUl0UGUxdHcKLS0tIFBrM3BpdGluQStydlVQQVNDd2dQ
        RSs2aWE3UU1VT2xzQ2l0d0FHUWVwQUkKT5aOkfhk8JgmaH4fwnSE0xzg6bVQ4Wi2
        2frXBclGHpe9g0Un0PaFrZoU+gjZYr60GVk5gjmqHD47wE1IrGU22w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-02T18:51:21Z"
  mac: ENC[AES256_GCM,data:G1WOsPaf+O5GhO+82jORX/ZsyQznkN5LJd7DL+008Mmdlx0eX9XYdFNEG1PKanTzyulW47Zodc+ACixg53H0hQ2NzuboQWwcIWYGoDFrk/Ch5kDsK9zVq7wl4chB9/iEu0lC6JXCgbmcgpkd9bmiOLBuLFgpxzlKiC9fxPVN1eo=,iv:RFsAG5Dbw36ywdfkpQs4pGWK4ndQjz7vHnNqux/vMlg=,tag:RTXw8jEd0Q4iErRZQYahOA==,type:str]
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.12.1
