serviceType: ClusterIP
routerServiceType: ClusterIP

defaultNamespace: health-system
additionalFissionNamespaces:
  - fission-gym

createNamespace: false

persistence:
  enabled: true
  storageClass: longhorn-r1
  size: 2Gi

storagesvc:
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

analytics: false

mqt_keda:
  enabled: true
