apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkitd-state
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-strict-local-wffc
  resources:
    requests:
      storage: 50Gi
