apiVersion: v1
kind: Secret
metadata:
  name: delivery-demo-git
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: ENC[AES256_GCM,data:jipA55baOLsp6CVdB1tGYIbx3p/1lt1OanBJLDhOIm995PrmzRSS2bHoB/wvHw==,iv:yXvNrr3cgPW79hlCEA9ORJ2QQigWlgvnsHqKiZ+c/1M=,tag:WtcCWkmJJ4r+On5pj57Zmg==,type:str]
  username: ENC[AES256_GCM,data:0r8+4W29KNc=,iv:rvjlcCXZCwvw+ApUk6fTuofzgJU21g1ismm4dlTonk8=,tag:TgbDuvq4Y+MKcFBaN9EpGQ==,type:str]
  password: ENC[AES256_GCM,data:MckcdwXE0Nu6VaVbJ9iYH2U3fUxtBHZVqf1sCmxalX8N2UMJ1Gkf0Q==,iv:rn92XgMVQCDbPpchU7sSckU17ZyIRpFFsNwA/y034GU=,tag:vwILBIw0aHtFQCAKi6nVoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNjdUQlpLeFJHTFM2ZEtQ
        a3lPK01EKzQvWWMvc2xtTzEvZTlQZ1NON0NrCjI4WllhYkx2WFdrWEgxY1MwRTY1
        MkVCM05lMW0wemNOcnE5OEJsQmFUYWMKLS0tIFF5NU9sTjZjMGg3bElVb1lnL0xp
        bm9hT21rOFRBMWdCQm9EWFJhRHY0Q2cKF82/HpK7WdSCEOrPiRfUQcJI0sEMbRcc
        hXvN4CXN91O4dDbpCjmQZahz0rbTMCILAjLWUdA/ai9nGJXB9GrCeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:06:47Z"
  mac: ENC[AES256_GCM,data:Hx0PG71IghGKlFkI4d2s0jZWQ+LFCqEuT1ZreD9lL7XKxYa8qLvfBituIc+hbR1E2IN4gWVyOYKHcGLUR9neFt/Lhrfrs/43Xba9NCuOWjiY0Tag6BDMQhY54TK5DA0IhEE5NBOYErBvV6iFs9xQIgPHRaoum6cKRkzxieY5sEc=,iv:X71h9Apu71QKMJRI3lI0+x1uv7LzlNdQmBTkwuX3P6s=,tag:ERWD2tAjJbfuzDwMo6f6FQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-hello-image
  labels:
    kargo.akuity.io/cred-type: image
type: Opaque
stringData:
  repoURL: ENC[AES256_GCM,data:EV60pvYuv5SABJbvhrwpi2k07yGhCL411uvYiHBU,iv:nMF5LUiPeVvL0Lhf4g473/9boUsSxUPd3lPcq1qkp20=,tag:SzkAZLiKWWgo37e1++7Epg==,type:str]
  username: ENC[AES256_GCM,data:GjNQRcZT51L8o3t424e06pFtT7E=,iv:UG1i+uUyL4LvFtW+SWaiCvOiIniASl/wiQzzN9vz1mA=,tag:rtF/ZJbk4OQIeuTQzG+quQ==,type:str]
  password: ENC[AES256_GCM,data:G0dY1/iBqpaIcBf74WjzKWqe9DuNG9khOpJ9WfuovcM=,iv:2vCoq2ugniGU7bRVDvTAiVaeMq7YJgQ2UG2ufivI5tY=,tag:9OO3n4GhOKo/r5eT0cae/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNjdUQlpLeFJHTFM2ZEtQ
        a3lPK01EKzQvWWMvc2xtTzEvZTlQZ1NON0NrCjI4WllhYkx2WFdrWEgxY1MwRTY1
        MkVCM05lMW0wemNOcnE5OEJsQmFUYWMKLS0tIFF5NU9sTjZjMGg3bElVb1lnL0xp
        bm9hT21rOFRBMWdCQm9EWFJhRHY0Q2cKF82/HpK7WdSCEOrPiRfUQcJI0sEMbRcc
        hXvN4CXN91O4dDbpCjmQZahz0rbTMCILAjLWUdA/ai9nGJXB9GrCeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:06:47Z"
  mac: ENC[AES256_GCM,data:Hx0PG71IghGKlFkI4d2s0jZWQ+LFCqEuT1ZreD9lL7XKxYa8qLvfBituIc+hbR1E2IN4gWVyOYKHcGLUR9neFt/Lhrfrs/43Xba9NCuOWjiY0Tag6BDMQhY54TK5DA0IhEE5NBOYErBvV6iFs9xQIgPHRaoum6cKRkzxieY5sEc=,iv:X71h9Apu71QKMJRI3lI0+x1uv7LzlNdQmBTkwuX3P6s=,tag:ERWD2tAjJbfuzDwMo6f6FQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
