---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  TALOS_DIR: '{{.ROOT_DIR}}/talos'
  PRIVATE_DIR: '{{.ROOT_DIR}}/.private'
  TALOSCONFIG: '{{.ROOT_DIR}}/talos/clusterconfig/talosconfig'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOSCONFIG}}'

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos
  template: .taskfiles/template

tasks:

  default: task --list

  flight:build:
    desc: Build a WASM flight
    vars:
      name: '{{.name | default "echo"}}'
    dir: '{{.ROOT_DIR}}/flights/{{.name}}'
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o '{{.name}}.wasm' .
    generates:
      - '{{.name}}.wasm'
    preconditions:
      - test -d '{{.ROOT_DIR}}/flights/{{.name}}'

  flight:push:
    desc: Push a WASM flight to GHCR
    vars:
      name: '{{.name | default "echo"}}'
      registry: 'ghcr.io/skel84/flights/{{.name}}'
    dir: '{{.ROOT_DIR}}/flights/{{.name}}'
    cmds:
      - task: flight:build
        vars: { name: '{{.name}}' }
      - yoke stow '{{.name}}.wasm' 'oci://{{.registry}}'
    preconditions:
      - which yoke

  reconcile:
    desc: Force Argo to pull in changes from your Git repository
    cmd: argocd app list --project kubernetes -o name | xargs -I {} argocd app wait {} --sync --timeout 300
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which argocd
