---
apiVersion: v1
kind: Namespace
metadata:
  name: apk-forge
  labels:
    app.kubernetes.io/name: apk-forge
    app.kubernetes.io/part-of: apk-forge
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
