---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zulip
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/zulip/zulip
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/zulip/helm-charts
      chart: zulip
      targetRevision: 2.3.0
      helm:
        releaseName: zulip
        valueFiles:
          - $repo/kubernetes/apps/zulip/zulip/values.yaml
  destination:
    name: in-cluster
    namespace: zulip
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
