---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipelines-as-code
resources:
  # renovate: datasource=github-releases depName=tektoncd/pipelines-as-code
  - https://github.com/tektoncd/pipelines-as-code/releases/download/v0.49.0/release.k8s.yaml
  - ingress.yaml
