apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oie.fullname" . }}-appdata
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oie.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
