apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oie.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oie.labels" . | nindent 4 }}
type: Opaque
stringData:
  databasePassword: {{ .Values.secrets.databasePassword | quote }}
  keystoreStorepass: {{ .Values.secrets.keystoreStorepass | quote }}
  keystoreKeypass: {{ .Values.secrets.keystoreKeypass | quote }}
