---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/kargo/kargo
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/akuity/kargo-charts
      chart: kargo
      targetRevision: 1.12.2
      helm:
        releaseName: kargo
        valueFiles:
          - $repo/kubernetes/apps/kargo/kargo/values.yaml
  destination:
    name: in-cluster
    namespace: kargo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
