---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: allocdb
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/allocdb-system/allocdb
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: allocdb-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
