---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-helm
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: codeberg.org/forgejo-contrib
  enableOCI: "true"
