---
apiVersion: v1
kind: Secret
metadata:
  name: kro-helm-charts
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: registry.k8s.io/kro/charts
  enableOCI: "true"
