apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: repositories-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./github.sops.yaml
