---
apiVersion: v1
kind: Secret
metadata:
  name: zulip-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    secret-generator.v1.mittwald.de/autogenerate: secret-key,postgres-password,password,rabbitmq-password,rabbitmq-erlang-cookie,memcached-password,redis-password
type: Opaque
