apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-admin-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  currentPassword: ENC[AES256_GCM,data:1LFQXJU=,iv:qRxu7phQqm2F+ohlv0xTaw9pxdHsvs0HBN4ZXCBZGD8=,tag:Hp7mSjekaGQbFi6wWhiohw==,type:str]
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVFBvdlZCUHpURkJRV3Vt
        d0JYVEJqcjFzL3lFdEtucGlIa2tVUFB6ZzNZCmhhVXFrSi9aN3QxTUpzYS9odkVL
        WWtTUUVvYi8xNDdoK3ZwcFhnUWNXL1EKLS0tIFpkOUdMOTJHejIybjJJUUl3ckpW
        Ylk1MnEzWEk0Vk1rbm1jVnowRkRnWlEKJ0XezXyOIIeIgSVsni8oIE0zO0bI+nd/
        6d5Fc/32ow3VgC0WMcrf4sBphMShlz+EiqSB9aDIxc5dAc37wELcaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:59:08Z"
  mac: ENC[AES256_GCM,data:Di5jMFqWCHjOnb0nqizR0RzZk4fCUX3PACkc1mofPB1ji22XpGTgbFpImRbkp6YRTsashax/qU5h507XJ/as0iZb4yUsOexKJjwz7Qgur0zCCzWN9VBTOXvG/sFsb4EGdEYlIst9XY4nwG1O+JGqB+AkX3aPFRlN6jgKGU0Ziec=,iv:9YcdqXrqqCC4E1UL18ZNquTgInBIE2bfl5FQKDNzwQQ=,tag:FODo80TYxvNEg248YfG8gg==,type:str]
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-monitoring-passcode-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: monitoringPasscode
type: Opaque
data: {}
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVFBvdlZCUHpURkJRV3Vt
        d0JYVEJqcjFzL3lFdEtucGlIa2tVUFB6ZzNZCmhhVXFrSi9aN3QxTUpzYS9odkVL
        WWtTUUVvYi8xNDdoK3ZwcFhnUWNXL1EKLS0tIFpkOUdMOTJHejIybjJJUUl3ckpW
        Ylk1MnEzWEk0Vk1rbm1jVnowRkRnWlEKJ0XezXyOIIeIgSVsni8oIE0zO0bI+nd/
        6d5Fc/32ow3VgC0WMcrf4sBphMShlz+EiqSB9aDIxc5dAc37wELcaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:59:08Z"
  mac: ENC[AES256_GCM,data:Di5jMFqWCHjOnb0nqizR0RzZk4fCUX3PACkc1mofPB1ji22XpGTgbFpImRbkp6YRTsashax/qU5h507XJ/as0iZb4yUsOexKJjwz7Qgur0zCCzWN9VBTOXvG/sFsb4EGdEYlIst9XY4nwG1O+JGqB+AkX3aPFRlN6jgKGU0Ziec=,iv:9YcdqXrqqCC4E1UL18ZNquTgInBIE2bfl5FQKDNzwQQ=,tag:FODo80TYxvNEg248YfG8gg==,type:str]
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.12.1
