# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:GkG7wkKAi8Mvda9M2l0KLy0qLoNWVlClgrEw5RysLLYPiWIaQXzpFg==,iv:uADY50vmAgAifturNuY2pOb+SJFdCzp5rdHCXfMRHyg=,tag:UAxRlqehYnUuxtuxaeHiyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aldGNmUzTCtTdEd2akpm
        YjhwdzdXZWRXbDR6aUFxT2tjODRuNlpiYWdrClRsNzRncXFaM1dMWkpTTXNublh4
        QmxsYXM1ZEpqSFBIUHdQZ1RaOENOWjgKLS0tIDNzc0lzM0xCRDlndzJEM09wSlFv
        VmRaOUZZcW9JdzQ2VFllS1QwTStpNVEKzytKhBKXQIchtc8m9wQSMxHMJpQ96tqd
        xZvZ+aSodWoOODB+arieqE1/d0PZRs6LUePp4v1053FCkxXmeJ8anQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T20:11:03Z"
  mac: ENC[AES256_GCM,data:E1M2rGfvcMPPnWlqI8Mts27ThGvNoYTwcaazx8P5vx6rNodB6kWImUh5Am2m2y267yS6h1I8rfkffBcEm2ItvmKe5CegFVi9PmRMozYCcS95LC+zuR4aM2LoT0BIFoRFpUDapDF4UPMu4yJ+t0IVnKj+nb2Tf8vXkECpobxI5kc=,iv:/a2R7AmCevtb89I9icT6lOWn1mo7GIjRxuAF3aLWNEo=,tag:+nFdQiXLloR+OL0jK5diuQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret)$
  mac_only_encrypted: true
  version: 3.9.4
