controllers:
  mosquitto:
    containers:
      app:
        image:
          repository: public.ecr.aws/docker/library/eclipse-mosquitto
          tag: 2.0.21
        env:
          TZ: Europe/Rome
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 100Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
service:
  app:
    controller: mosquitto
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: mosquitto.rbl.lol
      lbipam.cilium.io/ips: 192.168.0.56
    ports:
      http:
        port: 1883
configMaps:
  config:
    data:
      mosquitto.conf: |
        allow_anonymous true
        autosave_interval 60
        connection_messages false
        listener 1883
        per_listener_settings false
        persistence true
        persistence_location /data
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: longhorn
    globalMounts:
      - path: /config

  config-file:
    type: configMap
    name: mosquitto
    advancedMounts:
      mosquitto:
        app:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
