apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:dR/QtqpKX0RV8jfRsF9Ly/JaDXrD0OGPbvDHfVbDWb7e2SDDP5djPA==,iv:GfL7XWjV6s4IgitwYiFnk3K6+k/2TnjzOnWgObzw5Fk=,tag:8ScIL/2NBUfhmHZpiJhBXA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS1B5YTV6azQvN3JielFB
        UUZGUVZnNE1IQjNjQXhRdVBWdkRYdTkxR2tRCnVlaVB2bmdyL2F3QlBWcjZ5bzJm
        VklpMGFkNTVNNzBWYWZPdkozTDVhVXMKLS0tIGZZR3hxTmtRZjY2bTdCdEVRc24z
        YVV0ZGpYL2xiM2xuQlpkKzF2RklKU00KFcfagi7GkrxeMX1XgBPjR/RZw2l31V6j
        yabIlDEYnNt1KTCpuOPeuduFlkkBD5AP6nybLX2OeI1K8TksvpgeQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T20:11:03Z"
  mac: ENC[AES256_GCM,data:G0WXrZMJ7C+udWtnaqyaPbGK5b8SFPdK/jnnN17ftD0oe8JVXyn5HCz84+kW2MqlNmHPFET27rWItCKJbbX1h0mJ0PnEV4C56V2uEAw1NgRfVsCqNWB1r9Ft6RDoJn4PvG24mqAysaaea7IYnHtiw9fzh3qXbSxT3vhV89RHJUU=,iv:2mEh9zNmUxd0jkluxO51qpMgZA3kEaM5wisEo0/PjkI=,tag:83jhy5E9Muadws4OhpcUag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret)$
  mac_only_encrypted: true
  version: 3.9.4
