apiVersion: v1
kind: Secret
metadata:
  name: oie-config
type: Opaque
stringData:
  databasePassword: ENC[AES256_GCM,data:pOuRbILouMaDVDoGxPH/3PA+DKBL/a3iNStd7BMFILQ=,iv:iaeWTkjKe4oO75cawBd8WXavO6XBxRFj0vwAvM/MgsI=,tag:F7FX3Emx+AbYrdtdn4EZIg==,type:str]
  keystoreStorepass: ENC[AES256_GCM,data:JU2+08IKjWzzrPqVKFcyKptatbkJE6+yBKkDHhj1Nc4=,iv:MxvRWah4mYjRyQhUokM+mdqt47KYiHGX42j/6s0Pw1E=,tag:JR3aBB80ihwmQF74UISKLg==,type:str]
  keystoreKeypass: ENC[AES256_GCM,data:/lE1I9sEfYYmEdAspkKjE5yorIZ757aP1eOrDDYfd0I=,iv:S6dn4wNmnETkF6+UhfpeYkKinOhvufV7Fh5UPrSVSA0=,tag:KQQ9ox73UugFhzM6HIyGtQ==,type:str]
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRjRwUnRnQkRmM0swcEll
        bE9iVEJJRmx5U3owMTB2ZzVrSmtCZUZUWEJvCjhrelk4dWdvVmVqMWEwMW5jY3ZV
        cG9GYXdhMjhnVURzRlA1U2VXcWxRUFUKLS0tIEhtTytkbFBZaTQySWFaRU5DVkNH
        UmRIQTdHY3NlZ3d4TG9ZZ2lGazRtSXMKM0gdu9qZfE4JvgSoOdE4g3ciJUT5SUmG
        LDCNarmVRPvCTVdekbAZ1MlaWTOt9wqdZnB/BIfzPSPgoKAtpfVtrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:09:55Z"
  mac: ENC[AES256_GCM,data:P+46UvSSRuFp9Wq/J9dgwopZ8BvKIP86fivbV6GTCwY77tSv7XL6z18gC2WI5UFUOW7sqHZIDDUbbtxaEzHFriVYS9Olh5RsNFRmthsvp35jqxvqbBIs4TWIGJDdAGBzLOklcr6u7aYMBjYAUlezHyotLWt2OCrajxn1Aymqxzs=,iv:FwSixnLHM++ovZWFGxMS84fw8I1VgrkTJldlvCqmUZk=,tag:92HBNUHbm21Kn4nE2MTDUw==,type:str]
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.12.1
