---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: loki
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/observability/loki
      targetRevision: main
      ref: repo
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.30.0
      helm:
        releaseName: loki
        valueFiles:
          - $repo/kubernetes/apps/observability/loki/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
