---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: promtail
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/observability/promtail
      targetRevision: main
      ref: repo
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.16.6
      helm:
        releaseName: promtail
        valueFiles:
          - $repo/kubernetes/apps/observability/promtail/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
