apiVersion: v1
kind: Secret
metadata:
  name: kargo-api
type: Opaque
stringData:
  ADMIN_ACCOUNT_PASSWORD_HASH: ENC[AES256_GCM,data:XIXAmJWvl776HTOnXCIsOONii2CJ8Q1YCIlGNTnr5LZhNWEuYjanJYTX/xqwKqvW7tTIB80+6iqR83oM,iv:Tj13cz3v75r+PofQQ56felRoAeuTix1kDYXOM5iY1ck=,tag:DfWjvhIu1x5MgHY2PZD30A==,type:str]
  ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: ENC[AES256_GCM,data:KgrzWELlf9BtOSPz2DqIHDeH1pGoASxTt0mVu8Nl+bvboi8a4pLyDg==,iv:Iof1eVwL+IIGCjx+aPusPd0KFGJoHJXG02s89rN+zzo=,tag:OMopt+XGJFfxanW7rIT0TA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbWp0blJHc2ROaWJ5U1pF
        bTcvWVNBdXFkYXVoUFphQzBTaDVtcWRoaERvCnJhWHUzRitTS0hpL2RxY0FyZ3ow
        NVRqZDYxOVJCTkVZQWFDSXJYWTk3U2cKLS0tIHNjUzRFdzJPZWJpS2F4YWt0YzVR
        RGhEbjhnVUVibHdwRzVlUkNEMzVHRE0K44jewaUVvfO8mUgYHb4IFsuxVOQeYgHJ
        /dqT/dZqInht9r8BKZQDtF6sqEyhNBlJ6rJ4g5T9xp81Wo63UpFvBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:07:31Z"
  mac: ENC[AES256_GCM,data:XFoWiAV2KytiLk8BPDm+1sHwzlpw97v9e9Wlpa+NJNWxM/uTca2oOswyG9qtOeKUikdkHHSr6qexk7PTL9LgcRCget/eQ2cWk7g7DTjfK2LEbRZKmPbVXqVqpZuPPItkMoqY+gvnaS5TQY6biT+EmLHL4AUQfTSHS0Xclwa6xiE=,iv:rnzz/Almyb34TuHXEj/2IJUdakHvE80CoGMGMY6hs40=,tag:bQLgvAisQEFPNdeGqPhqxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
