apiVersion: v1
kind: Secret
metadata:
  name: kubero-secrets
type: Opaque
stringData:
  KUBERO_WEBHOOK_SECRET: ENC[AES256_GCM,data:FIdAb5dbvnLIkAd+GFANXp5BdZrv2NvTeKD/V91xgswbilQnzewMWkWcWHpr+yNOL1kvVZtLgy/zM/Wmpo57aw==,iv:XJQ1MuO3EAHiwVvokpNs7tg+3H2k6dxaeU2CvBFssPI=,tag:axIezcKrV3cfmQwdNdykEg==,type:str]
  KUBERO_SESSION_KEY: ENC[AES256_GCM,data:agGQT8LVBm52JadsRjo3hxNbbUE0KVXaRIRdy9b6UwY4YElZgBRd/Z+wMGu+JZ9oY4AxkXNwoEgWEk6a6a/K2A==,iv:fu3mYA6tuxtZx25LKltEqimS2lmDRxDuVDVGHkPH+y4=,tag:w4epB9I83dsU6BM9hzJFaQ==,type:str]
  KUBERO_ADMIN_USERNAME: ENC[AES256_GCM,data:0jLFmpY=,iv:bB3Ik+lel670p/nLCfTlfABF37BMwgf8arKnSWG0Jfc=,tag:rOaRjfWODgFnlkdvLeqeIg==,type:str]
  KUBERO_ADMIN_PASSWORD: ENC[AES256_GCM,data:cQswVc+tG8MSecSq7LYKjhC/KA5/nzP8gX0LFrw4qok=,iv:TbUtorHH+intL7qOPmIxUdhSXg8wZw4SorwOfmt+wYI=,tag:781ECtEa5CLMkPu6VF7jTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWEhGVFZrNWRJR1BneU9X
        dE9LVXlERDZpc1lwS0pNRlVLcXkyN0E5SEhzClM1K2lpK21vWWJVeUVldVlzVStm
        b1NpQTYxT0lZazcyRXEyV3RzZ1BILzAKLS0tIDRjaXpKUE1jMFRlNDFlVnVrT1Fm
        SDR4MzZWNTdCRzg4b0FjdnQrQjN1Yk0KuqhYBHhthS/S6EhEY84nFSQEngIoyzl9
        odjsk3rgyGqtZe6Gu2eQT0WlYwWqk+v51lNDEI4KVS71j+dDJOVPVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-20T12:08:45Z"
  mac: ENC[AES256_GCM,data:GmsNKRAQ2HDVyBC+d5h92JlScqaJ2k5EctGyW80LLF2aD3d+/9Gah8cnd7ENUdg0C0yNvEfjqnilAXznBrpeMp4vKq9iao+/pRc7j+TMvUiQTdMXvHDC9WSJiZPU+9pnLJ9/k6ucYHUtLkTXLT0BIeuyyRSAdzV1YfGU1VHe9hQ=,iv:bnwETjlxw3b5bJ3MfYwakdULBwmRUHaGNGIEuJ98Otg=,tag:U7TiUwcVX7I9yiShUheBTw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
