apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull
  namespace: demo-dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:l/0jzlxTVG0AwbmAZZeqKqKEJzO515ryXinKdZY9eteLuwCDr+bwowWX/1EaQ5LigStSpOWOTLxEaquoCi/PirqBsiYhpnEhrcnhmUjrNqOvKEkiRFKo2uqFKLNrcJ0f0PQ4+egUS+AmLBj/kN7qMwyQh1hnS1K6Jf47T8QtBE8HGQgECl9Z5pKw0EDZHlXHgczfWoVEAbLnxAj1IraDKXMfpGSL2uy26mbqAPpBqiYIr4VktLtDQ0MGKsiRsK9b,iv:/kVDk1+cP1CsKX4LVgmmMSPnNxXA46CauDUoqb9s2co=,tag:YzA7azL6Gt7eGwym9u2LTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZjd3WndveVFCSkJXdFR1
        T1FMVTExQVdQbDBGbVBaVHN5TUVyemp2YlNBCmZ6b3dEZFBmNWIyK2dqeEwyR1pP
        bGV3QU9pQnRDWEEwNWQyaHhpSmp2N0UKLS0tIFJ2NHBQNFQ0eDMweE5xOW5MeUN1
        NkpHeisyaGxSbDA0TDM1YkRualIzTE0KnUvleD7Sd22Ghk31f3KifhhBbZyq+Ust
        iOEAzwTj7zziGK3buKphXkrw4JXnVGrbz16vN3oOpw8zjUChnnZ+tQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:06:47Z"
  mac: ENC[AES256_GCM,data:uSMXnebo7E6B/g88VOVpjGMIyKOoPh6EoGrDMA9TcJQQBHviEilK1UnClSFDhIKAjDy3L4cLoAJnSskVymRpmdXv/2y8tFX9cjSHJmFmom8D133SQanJmwAhIRoddFT1jSu7bnFMC7bhw7UngUAhbBdQr9bKna1rp3JMXZldkag=,iv:K0S4og0Voh53FrUQI/8NGmscegrct5ILtfS+9HA7u84=,tag:okzO9Ha3RK4dGqTTg7Kfxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull
  namespace: demo-prod
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:2T9p2qVwvXAUGXJeR/rsW66/BvqssmWuddLBEGGecIgLBpcQldqsSC8RaKV6DixKqIfJKhYaxGmnymjptZ2UUXyF2LytUKTMoOG9xwuwluXjzM19O6cy+scloblnhriZwnFRepe0JdqaJ6ci7GJ0iv0vD0Hk7QXx7pHD8JCnp0jujtcXgLkv+paeg8uzehV3UI5g0CS0azmGTqva8O9GO38IX5rEBMwifGqH7ptE8zeABnp5H9dDuXXQj4A5YUtV,iv:f5JBRx1kTF+HAdThz9spcE9Gz09ryq69dUq3pcrKpSI=,tag:tRT9+YFfvApkbO8EADAEWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZjd3WndveVFCSkJXdFR1
        T1FMVTExQVdQbDBGbVBaVHN5TUVyemp2YlNBCmZ6b3dEZFBmNWIyK2dqeEwyR1pP
        bGV3QU9pQnRDWEEwNWQyaHhpSmp2N0UKLS0tIFJ2NHBQNFQ0eDMweE5xOW5MeUN1
        NkpHeisyaGxSbDA0TDM1YkRualIzTE0KnUvleD7Sd22Ghk31f3KifhhBbZyq+Ust
        iOEAzwTj7zziGK3buKphXkrw4JXnVGrbz16vN3oOpw8zjUChnnZ+tQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:06:47Z"
  mac: ENC[AES256_GCM,data:uSMXnebo7E6B/g88VOVpjGMIyKOoPh6EoGrDMA9TcJQQBHviEilK1UnClSFDhIKAjDy3L4cLoAJnSskVymRpmdXv/2y8tFX9cjSHJmFmom8D133SQanJmwAhIRoddFT1jSu7bnFMC7bhw7UngUAhbBdQr9bKna1rp3JMXZldkag=,iv:K0S4og0Voh53FrUQI/8NGmscegrct5ILtfS+9HA7u84=,tag:okzO9Ha3RK4dGqTTg7Kfxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
