apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/Media
    server: 192.168.0.217
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: media-nfs-pv
  storageClassName: nfs-media
