apiVersion: v1
kind: Service
metadata:
  name: allocdb-internal
  namespace: allocdb-system
  labels:
    app.kubernetes.io/name: allocdb
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: allocdb
  ports:
    - name: control
      port: 17000
      targetPort: control
    - name: client
      port: 18000
      targetPort: client
    - name: protocol
      port: 19000
      targetPort: protocol
