---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nack
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/fission-gym/nack
      targetRevision: main
      ref: repo
    - repoURL: https://nats-io.github.io/k8s/helm/charts/
      chart: nack
      targetRevision: 0.34.0
      helm:
        releaseName: nack
        skipCrds: true
        valueFiles:
          - $repo/kubernetes/apps/fission-gym/nack/values.yaml
  destination:
    name: in-cluster
    namespace: fission-gym
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
