---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-smoke-test
  namespace: argo-system
spec:
  project: kubernetes
  source:
    repoURL: "https://github.com/skel84/home-ops.git"
    path: kubernetes/apps/ci-smoke-test/ci-smoke-test
    targetRevision: main
  destination:
    name: in-cluster
    namespace: ci-smoke-test
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
