apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: postgres-password,password
type: Opaque
data: {}
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK0xNdjVKMVBuYUl1YW9I
        ckRXNUlLT3B6M3FoVmNNZHhSSWZHeExlbjNVCmxrTDJFTTN1VE5GYkU5NlY2bGlh
        SnFGdzVraTFpZmZza3BpTm5HREsyTWcKLS0tIEJKM3h2Tk1HZWtlZlZ2ZURlYXpa
        ZC9laE5rbE4wQ3RyREY2RnFxNE5kcncK6BuXqYyiiL9c385ewkmCWN32laQ0EfBg
        y2KcUWsx4oqa7xCG8GjP2fZPiw2wPssKPh1t+Vl12kyhwyXpqPLYTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T20:59:08Z"
  mac: ENC[AES256_GCM,data:Svnec7f06szek3DBr0yTWLicrsEEQ5k28+VgMSczVVmyc3YgoadQgtCPLgjTDJDJdhGNMnNNgd4UZQefJCJENtsfxy1VuDT6UH46lT2xfP7rA2eIeyDvRb3oTelKkMhVfSeXH6L9Tg/1Fe+LNiwZo0srNMKAvDlIEud+bgYW/w8=,iv:T568hn/AqgKnlU+hwaIdLxbllgrf1sYdg0gYWHpRu+A=,tag:TbqradQEaz6nsLAbqTA47A==,type:str]
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.12.1
