apiVersion: v1
kind: Secret
metadata:
  name: forgejo-webhook-config
type: Opaque
stringData:
  provider.token: ENC[AES256_GCM,data:8JLMyxlvCRHVqKfp+rvU91Ixp6Umbaok6Q0vwi3f30O8rtQr2UHuiw==,iv:RItoavPbWDwWZT2OIK9pGwASrly8cq49gd/WOLVygW0=,tag:qzuDxXTd4pkLQjCb2ESwmw==,type:str]
  webhook.secret: ENC[AES256_GCM,data:lidSaWDaXi3BHwH44nbixKc8+vx26t9ARcpK/Qarf3SdiKQl9rQOqA==,iv:5pbGLcYXiJA3XvElrpTt0ZXlpsUKBT6QCqDXeHpBDxk=,tag:Vrvxd/tDLtKVxokbAsJFTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZTJTcGJkZEFOSWRxZWx4
        NHpvWnJhbngyNTRuZnRyNjNJc081eGoya0N3Cll0aExxakNBVXBjUThWNjI5Rktv
        Nk1FUE81d3dWTkVqYzczTFZucEE3bTAKLS0tIHVXdjFqT2FzYnVzQ1lNem9aK2Vy
        cW1QQ2I2R3Z1YjdlUm05SGR5K1VmSFEKG2/+9wxZcFS+LrnRZveYXOBZkY2Np+yd
        u4uem0jgaPICEfNDVABI8kHCOsZqXP4Dig/dq3x1HmvelIblyt1uJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:06:47Z"
  mac: ENC[AES256_GCM,data:UMeGahGUnI/3p7lT2JvWUKXDEStO15rqR1cx4MKj7o3YOwdy/dY1jUo8NkNdy9U6O2/S5vXOS0DelyLw/w+1Jsi2QVvbrtUs1DWByvFB5Y7wVGrPnbp6VIi9wuFZNjItFXCpV26MsOEPMiebnG6hxsy9+NxK1mpf64AZMZiOj/4=,iv:IprD/x4qdPvyurPF2Ps1ir5vXt/TaSqhuHgC/ywFbyg=,tag:PGocLvkADMc4Vy0ra0aRJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-push
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:MnmanYIi6ouql3uDBqsUgqSyr2jx/uyXyhzgJ83fn8w7PV+2E/uxWs/SkDYlcEKgxElggh5XrtwQbhwrpuuNot3pF3AocHQ15G5jHGLuSKwnvemF2b+/1vGEw6nZz6McKC3n1LIi//mh9MnSkPsxvKwUqtRY8ujQF3WjGn39TJDYmnTQMttvgF6AblmLkHy+jFJ5IQM/24qbQvegxy9OsS7CJltjO4+OiPN2XgSF/ZZ11+qcZ2tZX1HKkjJmycQ7,iv:Ind7zeAwE+rilZCX1jD0Sij7cHPT9kR3vbTeuPLf1ic=,tag:AVUAgcGWdIsH2S2KlNaa8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZTJTcGJkZEFOSWRxZWx4
        NHpvWnJhbngyNTRuZnRyNjNJc081eGoya0N3Cll0aExxakNBVXBjUThWNjI5Rktv
        Nk1FUE81d3dWTkVqYzczTFZucEE3bTAKLS0tIHVXdjFqT2FzYnVzQ1lNem9aK2Vy
        cW1QQ2I2R3Z1YjdlUm05SGR5K1VmSFEKG2/+9wxZcFS+LrnRZveYXOBZkY2Np+yd
        u4uem0jgaPICEfNDVABI8kHCOsZqXP4Dig/dq3x1HmvelIblyt1uJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  lastmodified: "2026-10-06T23:06:47Z"
  mac: ENC[AES256_GCM,data:UMeGahGUnI/3p7lT2JvWUKXDEStO15rqR1cx4MKj7o3YOwdy/dY1jUo8NkNdy9U6O2/S5vXOS0DelyLw/w+1Jsi2QVvbrtUs1DWByvFB5Y7wVGrPnbp6VIi9wuFZNjItFXCpV26MsOEPMiebnG6hxsy9+NxK1mpf64AZMZiOj/4=,iv:IprD/x4qdPvyurPF2Ps1ir5vXt/TaSqhuHgC/ywFbyg=,tag:PGocLvkADMc4Vy0ra0aRJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
