apiVersion: v1
kind: Secret
metadata:
  name: forgejo-scm
  labels:
    appstudio.redhat.com/credentials: scm
    appstudio.redhat.com/scm.host: forgejo.rbl.lol
  annotations:
    appstudio.redhat.com/scm.repository: ci-smoke-bot/ci-smoke-test
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:BNFM9zX+j+l3XpprYD/zhvphqV/pL3j8TxrNYknR5U0M/dpJ84mucw==,iv:QrOYst7DLWUnmaqx0SMkv+O7f/uuYkIq0EaR5uF9AWM=,tag:WhwOP23gj+Qr5t7AeNxsMA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzRWUzZFWFJlYTNxR2d3
        VWxQekNWSk43bFpEWjhnbXF5Wk1TRHlzQ0RjClZFd05kVjUydml4VlVxaWVqUjlw
        RDE1WllWN1J4Wk5yYW1jZnZTVm9aM3MKLS0tIElwQUVOSnhRQ3ptcFpNYTk3eWJy
        c2ZSRHo1OVBrRnlwandwNmhyd25CL1UKYGxtxCYwQtZCikmAPfAr6mB+iOqJfRHW
        rR7hJCFK30o0dDWe5rFusLCo1eDOoCHKEyFu+/J1THhZKuNp5eItIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-16T13:33:00Z"
  mac: ENC[AES256_GCM,data:NAMyqJ3NkCqj1Sp5fCci0j/aN/KdG05zDSkq6RpHjMqX9Zg2QC1y67OR9oE2GeANGhBRVvjQDpHi73cuFwRx7F5GXZpcF7JJSXAiWsQf1ppexUZE3ycc6penkss5IPRHIuzkaliPupmZTGiSraMt4i3S6fORnVbPMZpnikQ8SEY=,iv:Oak0I+NFglaTOEY8DavYDV5zLseNLJh0TcTmlgQdDZU=,tag:qUC8s//Bcxs/jb6518jYTQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-push
  labels:
    build.appstudio.openshift.io/common-secret: "true"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:DxtDFB0FNIInT2mo697bvCT++FYNjnjkPfC1JHMYStsuA7iPzlUi/NkErfquQU/JUxLJ6/80+59Ceipf+Unc9moU1nwk3l6zp1eZp7fIIO5sk7l4c6PxskOthPkEovEsAnR2AUL5I62oJAW1GUSXiRqdHCoMAXkUe/3cioqcsqzRzmSwjnQgAPfxri5U+L5pi4nDr3UHB0ViaC/BNNaExum2ptqoD7k7NpnXwGHiTSAsX0xc5g9vi1+fcxB/vDuEa1opVtI6981P9wMbZ5fQHB+6BAqgadROxJLVSRkF66rnscL7bYVRWAho,iv:EfjF9wBmZYLwIYsMXGc48HBKtHuyF+2Wd0Gmwruf0L8=,tag:YYu6NMWlSWe7OkLbEiWHIw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bzRWUzZFWFJlYTNxR2d3
        VWxQekNWSk43bFpEWjhnbXF5Wk1TRHlzQ0RjClZFd05kVjUydml4VlVxaWVqUjlw
        RDE1WllWN1J4Wk5yYW1jZnZTVm9aM3MKLS0tIElwQUVOSnhRQ3ptcFpNYTk3eWJy
        c2ZSRHo1OVBrRnlwandwNmhyd25CL1UKYGxtxCYwQtZCikmAPfAr6mB+iOqJfRHW
        rR7hJCFK30o0dDWe5rFusLCo1eDOoCHKEyFu+/J1THhZKuNp5eItIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-16T13:33:00Z"
  mac: ENC[AES256_GCM,data:NAMyqJ3NkCqj1Sp5fCci0j/aN/KdG05zDSkq6RpHjMqX9Zg2QC1y67OR9oE2GeANGhBRVvjQDpHi73cuFwRx7F5GXZpcF7JJSXAiWsQf1ppexUZE3ycc6penkss5IPRHIuzkaliPupmZTGiSraMt4i3S6fORnVbPMZpnikQ8SEY=,iv:Oak0I+NFglaTOEY8DavYDV5zLseNLJh0TcTmlgQdDZU=,tag:qUC8s//Bcxs/jb6518jYTQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
