apiVersion: v1
kind: Secret
metadata:
  name: plex-claim-secret
stringData:
  plex-claim-secret: ENC[AES256_GCM,data:XA9/WnNI6JVAeeMvxvJR46sRzdiCYVYSAiY=,iv:aa/AIx7yzY5A3XwOaLfKhfHE0OfcXNSIXplW0rabtmQ=,tag:tj8++9wDq3QTUAMYGhldkA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS0VCVXQ2Z0Z1U0Nxckw5
        b3RPdklnQU52QXd6WEpIS3JRRmhhcU4xK0VRCnZvM3U4VlZBVEhXSGVDZUFKd1Rq
        dFdWTS9Dd1V4emhmWWF3SC9wRDJqM2sKLS0tIEFnWDBBRkh1NlAwY3NnRmhvSGxR
        MW1JcG5tejRDWjI5RHVRZFcrd1pJVGMKpCB0IYTgXlDfG+TZGlXDTfOuO3ftKsgB
        z2cpRCo8Dxn3Djy1U8CPUQBkm7r/1/F4/2pq4h8dSVSoXTUrGJGhSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-16T16:16:29Z"
  mac: ENC[AES256_GCM,data:zcKnoNiHkbgTF75Il1gQKP/PbV/2yif4VcshsF03K5NlbiV+fnuyOTvDX/Tlo12FHSmKjauBgxgDurM892n57QnbsBnFTgUo2eHnNEWRuNvAUNGDnsfBd94lDE2deKqqLmJjHC8xOR2+Uvdi5HclIuwmsGlU4o2og7zGlZ2CGrY=,iv:MVPb7Nl3Avt3q9J2HcdMqd10xqsZz2iTo3H2Ih8TvJI=,tag:uHJM0BIqxr6z07ZtLVqxMA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret)$
  mac_only_encrypted: true
  version: 3.9.4
