fullnameOverride: external-dns-unifi
logLevel: debug

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/kashalls/external-dns-unifi-webhook
      tag: v0.5.2 # Use the latest stable release
    env:
      - name: UNIFI_HOST
        value: https://unifi # <-- Set your UniFi controller IP/hostname
      - name: UNIFI_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-unifi-secret
            key: api-key
      - name: LOG_LEVEL
        value: debug

extraArgs:
  - --annotation-filter=external-dns.alpha.kubernetes.io/target
  - --ingress-class=internal
  - --ignore-ingress-tls-spec
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --events
  - --ignore-ingress-tls-spec

policy: sync
sources: ["ingress", "service"] # Watch both Ingress and Service resources
txtOwnerId: default
txtPrefix: k8s.
domainFilters: ["rbl.lol"] # Only manage this domain

