---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: melange-build
  labels:
    app.kubernetes.io/name: melange-build
    app.kubernetes.io/part-of: apk-forge
automountServiceAccountToken: false
