---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: support-access
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/skel84/home-ops.git"
      path: kubernetes/apps/security/support-access
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: support-access-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
