---
apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: ci-smoke-test
spec:
  url: https://forgejo.rbl.lol/ci-smoke-bot/ci-smoke-test
  settings:
    pipelinerun_provenance: default_branch
  git_provider:
    type: forgejo
    url: https://forgejo.rbl.lol
    secret:
      name: ci-smoke-test-forgejo
      key: provider.token
  webhook_secret:
    name: ci-smoke-test-forgejo
    key: webhook.secret
