apiVersion: v1
kind: Secret
metadata:
  name: ci-smoke-test-forgejo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  provider.token: ENC[AES256_GCM,data:hOvVvj4Gtj9/xH2Wz5ROqNBuc3yTx/Y94cSLyW6IWW2H9iKarAX87g==,iv:nXOE65pYF2kp3uGT6fXwQfLkCbxSl6ASC4Nnz+m+pBQ=,tag:yDNE2SkeaJv+1HMOKHKeeQ==,type:str]
  webhook.secret: ENC[AES256_GCM,data:Ovd+cABnU9eQnEd+VSVssIkaPqgZwdg1o9DnTyB/4jJwFWsMn4CV1jSBxDHgMuPIpQDT3sq4D198nkjKVEMIvw==,iv:v668AcNwG+yR7UVTNQac57nkdj1cb7HO3GIeemPM0Xw=,tag:6xPx8RD759HM0eEKLOkMYQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ2hLbUVaQjZaLzJBUUZS
        WjE4cXVKdnpiVGtBamhzM1hCVDMvZUJtMG5rCmQwNS9IRE1MRC9PRWdaQzJrVXcw
        SFY3eFN6T3RmdEpmZy9LN1RUTHlITkkKLS0tIDRZM3l2N3Uwbk1EeXgwcG5KT1BV
        eHpUeEZkWjBjMU5pd3RxUUlmZXMzMjQKH93lMJBCBeifgpGOjdZ8jrF28uzsycCv
        s7qkyfjdje0eub09okAjdlVi+8/CzSmqXvfq6dHm/PaQJ1AU49Kn7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-16T12:06:42Z"
  mac: ENC[AES256_GCM,data:eeQr+aheBW0vvoKoFfhPcEvjrsCFXsXEyVKyY1E/TDP8DvqAJdQRxl21Jk99t1V0uWWTUyzkRkPJvBNdqhzP4g+Xyc+4VMz/StH1FZZ/pj3v+IQwsFUSMichZhWvW356k6TeLa8GvcNwWRBACK3R7iUhnNaOFfOPhDy1ouKr1zo=,iv:qKz43wbFwTlUjKA/4h/ND8H7eqVyCvCwzgJfcmmsDKo=,tag:YGChrTK/YA60CoqwB8gZ8A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-smoke-test-harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:2nrKMVuhSVtzf1zLNYuZsD+BXLxEjrwLBySHy2JcGVfMmYWuN1a6uKHgHPSdhU+Kg3zZR18PovobAMXorqRCDMiAPvMM2hx4GoqVZNyPU6hFbctzRR7vLFWny15/NYk0EpWkNVjy54N/41MeW/RMgMZFJ15iZXBYKlyTpitzoVBAzO2QKfj4MnOuLshzR3xwRBgmvuWmFIzdTYEz95xI5e6HtMW8JjtyOizqf7tK2FIUrfB04CFcxs1x0VRzB56GA/jIjItPzw==,iv:j+CiuDkpLCX186idGqkkBBne69Wz9klDTLCcIfc3RZs=,tag:NvQd3rhi0ZPANNwrtzdr6w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ2hLbUVaQjZaLzJBUUZS
        WjE4cXVKdnpiVGtBamhzM1hCVDMvZUJtMG5rCmQwNS9IRE1MRC9PRWdaQzJrVXcw
        SFY3eFN6T3RmdEpmZy9LN1RUTHlITkkKLS0tIDRZM3l2N3Uwbk1EeXgwcG5KT1BV
        eHpUeEZkWjBjMU5pd3RxUUlmZXMzMjQKH93lMJBCBeifgpGOjdZ8jrF28uzsycCv
        s7qkyfjdje0eub09okAjdlVi+8/CzSmqXvfq6dHm/PaQJ1AU49Kn7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-16T12:06:42Z"
  mac: ENC[AES256_GCM,data:eeQr+aheBW0vvoKoFfhPcEvjrsCFXsXEyVKyY1E/TDP8DvqAJdQRxl21Jk99t1V0uWWTUyzkRkPJvBNdqhzP4g+Xyc+4VMz/StH1FZZ/pj3v+IQwsFUSMichZhWvW356k6TeLa8GvcNwWRBACK3R7iUhnNaOFfOPhDy1ouKr1zo=,iv:qKz43wbFwTlUjKA/4h/ND8H7eqVyCvCwzgJfcmmsDKo=,tag:YGChrTK/YA60CoqwB8gZ8A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
