baseURL: https://plausible.rbl.lol
# Must be exactly 32 bytes
totpVaultKey: ENC[AES256_GCM,data:WV5fr9qNtzlMKG/mY5ciX7SohLwHvzb0bgi4nW/pPm4=,iv:THnPNQjPNopb0JTTVi3HI5QGxnAKBhWsCRTQy8MbyN8=,tag:KA76kBX3yLgDJHO8ZYRu4A==,type:str]
disableRegistration: false
logFailedLoginAttempts: true
databaseURL: ENC[AES256_GCM,data:4Ts/gTMVixwTVk+qvUWZ/2u9orX69U9Cd3oAogDn0Zn3pU+SN/lYS1tO1UrkpAj3mM7KGcUz13Kr6LCHKgLIiZxR9w==,iv:ZBDNgQE8psjW1BsOumgCzfQ0H9Wdg4xWfmVJb4PsQdU=,tag:FRsmDcS5zCu+MlCKLoy97g==,type:str]
clickhouseDatabaseURL: ENC[AES256_GCM,data:ScxayDHvSFACsH3FxpC4ZOi3im4hSZyiNEtGlRVIkzILZOxolPAaSNUrQPfvYlBmFJgZ4E0VjX9PG0UkX3ABzr+hvkznk/qa,iv:48CoWAFlneVPEygHJqzsCFfgDATkb5lz0e7cXYX6tBg=,tag:WKDxLPF4xHOt0NK7pvevGg==,type:str]
secret:
  create: false
  existingSecret: plausible-plausible-analytics
ingress:
  enabled: true
  className: external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.rbl.lol
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - plausible.rbl.lol
  tls:
    - secretName: plausible-tls
      hosts:
        - plausible.rbl.lol
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
clickhouse:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraGFMdHZOdnMydDlwQlEw
        YnJUN1gyTUNJc3NhblBPWUtmNU1iMzhZNTBjCkIxVCtZRFFCV25wK25rZi9DWW80
        MHNhcHQwMkwvazQ3TkUzTGNQdW8rZDQKLS0tIEI2SzdWM3Z5Vy9Dc2svbFRQZzB2
        bmtMOGRKZ2VGRlRnbDJyY1c2bFdIWXcKs/3b+dBjJ7UEK3wythm15GM9CwUrjVAl
        THQU8XMJLFmWeMZhszoV0Y0x5NDWRWilsJxD7GqJGqjDDGHdlVnYag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T21:21:27Z"
  mac: ENC[AES256_GCM,data:4X7atp07C/JDshQ0R2ChUxs196f7UIh1PvmIviQxaN+tkpJ1Hmzn4nTOqcP5gE0qcGdEpZl1XpF2AyzQDar3EiEfAR1vOYzsYOx/NIXVD8QvpUvfk7zd3GoI4aEaS7CKFVSftJUWa93abvVFpFct6HXs93mPLFU4m2JBl77wVL0=,iv:JE/zoMcDa4ygsova+HN7ihT9crei599r4Otmx5Yr46I=,tag:KZ6e+jv91UKmgczkAiDNBw==,type:str]
  pgp: []
  encrypted_regex: ^(totpVaultKey|databaseURL|clickhouseDatabaseURL)$
  mac_only_encrypted: true
  version: 3.9.4
