baseURL: https://plausible.rbl.lol
# Must be exactly 32 bytes
totpVaultKey: ENC[AES256_GCM,data:RelOWhQcXp51DH4i/RU0U1w5dyNcuRg26ewFvhAbqa6OsSCBVTgwK+Ff5gA=,iv:Rt+/KcjCsU/pOxvTFKY5vqRs9HtKmtKFlLmI8CnCSWM=,tag:S2N1ziu/Bwp+t7y5pRrUSA==,type:str]
disableRegistration: false
logFailedLoginAttempts: true
databaseURL: ENC[AES256_GCM,data:A65fS+NuodTln1It53dgdHX5XzNq8U0n7TnB8BqnKTHCZ5iPmXBKPmmX2GzVuDHkORRmWwH9ACgFhw1xv2xFWOVFvw==,iv:6061yB/JQlN+rI6eWUdLLArPV2priXlSvHsfyYjkslQ=,tag:mebjG/HTTBzBn5Nj1j9ZfQ==,type:str]
clickhouseDatabaseURL: ENC[AES256_GCM,data:qtZ9f0ZSb6VAQu7AG2SlWF2r84bSrhAYdT8t9QlXZ7lTyPQ8wyH79VbONuMA/+8H7sFeJGWm/wp6v6fseIdEix5SnkYYqHdt,iv:zjbHD+4EzFactDn592jNzlUfZJSPzqQqe4P9eOOpcG8=,tag:bxWtnB7bLOK+7WFyI4WqHA==,type:str]
secret:
  create: true
ingress:
  enabled: true
  className: external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.rbl.lol
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - plausible.rbl.lol
  tls:
    - secretName: plausible-tls
      hosts:
        - plausible.rbl.lol
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
clickhouse:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXhkRk5WSTVyZFBpalU3
        cG1OMGZ1dlcyOTFEOE52TVloRWZtUUhhS1ZvCnVMRlM3ckZ2ZlR5S1ExQkZ1bEUx
        WDc4VGV1QzZMai9JWm9wNzZrQ09mNHcKLS0tIDFWaGhOYlhhbnNha1BjUlVDMlJF
        d2huMlNybCtNc2FvbjB5cGEvTGEyTFkKFjYQF2r2cQxiUbhxkPxojUuuNj6qb/AS
        kwNJuGyuzeox5o99EP+Y8o+5rLki4LUXI63ngAs9nxTWhWoPddPH1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T21:41:12Z"
  mac: ENC[AES256_GCM,data:hpPynIz6iS2pRmWV7BJ3I0y9aKh68ZzrdAdHcrkiLrLUBjv2wkARBVGPM8fLTktmlJIdwXvTEHFqKSP1r2yP6IzxW8sRaFsrISuZWN17w0vbTuIJ9/rkMBvYoR27hWExbJbvcqtlEaMfHHEDOjbdf9u0+haUZBXrAtYGhVgIsoo=,iv:8yM3iXvml9os3Qr2vWt3a6UTleSj2HS45ZX6QDXPtV0=,tag:sYSsPZR78c/FpOOXzrYGDg==,type:str]
  encrypted_regex: ^(totpVaultKey|databaseURL|clickhouseDatabaseURL)$
  mac_only_encrypted: true
  version: 3.12.1
