---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-admin-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  username: forgejo-admin
