apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  REGISTRY_PASSWD: ENC[AES256_GCM,data:/G/FZL78KBXLXNGmfytSY+AmqyLC6QTelh41YdeYdQE=,iv:UIyLrGDu4OA32Xe+ba/oE5+e0jpw8KrD+T76awzas2U=,tag:tGJWIHe0uPZ4p2pxxteRXQ==,type:str]
  REGISTRY_HTPASSWD: ENC[AES256_GCM,data:dhcaVuByjgE/WxuHMd5Xx17r9XrSHk/nBASF4LvLo+z23smye2nx0dtE+0p6c1WZ+/Qm3y88Q1scIX/iPTnpv4Ke5mNBZD/9HzHW12Mg0BLO,iv:lG7AeBQuK+6ZWd9LwVSplDSpUQPP99Cc77tdvNVISVY=,tag:Krdw3raUEL8yzlUEJpQCuw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZGJwTzdIeEsvVTFtZHM3
        V05McnNSM21NTkZWRUpCRnBqaXRXNXF5ZHdzCkkvZ0o0QUpMS2QzNDVtVnR3cERs
        NnRwMWhQUnE0WGZwM3IzbmNPYXgxelkKLS0tIDZldW13TmRRNFRha0pJQ0piZkhh
        SkgydE1SdXk2dlJKdDE3cjVBb0NVekEK4oM4MOC5dgoIsPbq96PeOl4ZxG/U/xZd
        /+6s0FY2Kn/35DY/KDfG3L/IOiwFAs6yzsZ64DMfHLATgohXCe+wlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T20:03:04Z"
  mac: ENC[AES256_GCM,data:qJFPUesSUhHJAlyfQyVP4r4kpbb5bY85n1yRMqo2Zri4Smz12aXqmndUrVYi74GDOoL8atG2VmJ+lQlKG6Scro16tdWXKqxLkvuLAq2kgtXZ1UThFvO38y7ojcTTulQOBVdHerT9M1i3dkpWySrbJKOsP6D2I4OQ1X2bjbsKDZo=,iv:phFZvWk9935zxLea2yYCHGFKuQZzLMxBnyTAm+vueCk=,tag:r9lEJYbv9x7Uw++bkkzEjQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret-key
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  secretKey: ENC[AES256_GCM,data:nrBM9fbvkPG72hcJ069Xpw==,iv:2o09noFDB002FbU4YSgz5GlK7X1WdwkBGW4aI1sIrdk=,tag:tkPIFSt0BOwdQsF5Dj/2Nw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZGJwTzdIeEsvVTFtZHM3
        V05McnNSM21NTkZWRUpCRnBqaXRXNXF5ZHdzCkkvZ0o0QUpMS2QzNDVtVnR3cERs
        NnRwMWhQUnE0WGZwM3IzbmNPYXgxelkKLS0tIDZldW13TmRRNFRha0pJQ0piZkhh
        SkgydE1SdXk2dlJKdDE3cjVBb0NVekEK4oM4MOC5dgoIsPbq96PeOl4ZxG/U/xZd
        /+6s0FY2Kn/35DY/KDfG3L/IOiwFAs6yzsZ64DMfHLATgohXCe+wlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-14T20:03:04Z"
  mac: ENC[AES256_GCM,data:qJFPUesSUhHJAlyfQyVP4r4kpbb5bY85n1yRMqo2Zri4Smz12aXqmndUrVYi74GDOoL8atG2VmJ+lQlKG6Scro16tdWXKqxLkvuLAq2kgtXZ1UThFvO38y7ojcTTulQOBVdHerT9M1i3dkpWySrbJKOsP6D2I4OQ1X2bjbsKDZo=,iv:phFZvWk9935zxLea2yYCHGFKuQZzLMxBnyTAm+vueCk=,tag:r9lEJYbv9x7Uw++bkkzEjQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|githubSecret|bootstrapPassword)$
  mac_only_encrypted: true
  version: 3.9.4
