apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    secret-generator.v1.mittwald.de/autogenerate: HARBOR_ADMIN_PASSWORD
type: Opaque
