apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: harbor-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - harbor-secrets.sops.yaml
