secrets:
  databasePassword: ENC[AES256_GCM,data:UVW/JPGuy70PBoXXwldiehWhMoqkRJ900+f23v5ZkyY=,iv:WnkB7vbtcojRQG00QcnhggOLWA7zZ2yHcTNQC5uwOv8=,tag:wjeKiOYCiXDrH4w+UHez2A==,type:str]
  keystoreStorepass: ENC[AES256_GCM,data:x+MfLFGDqBk5bjzE4hewVj4yYSXTwVJS67mS7pWaGpY=,iv:p0knznR2JRt73yzvI57xQHhh5qIpyCEN4PNpw3XOAys=,tag:TVXTFxDDN676xCeQVice8g==,type:str]
  keystoreKeypass: ENC[AES256_GCM,data:q8Xz7qN7ms9BxvPC7N7hOzkziYXe6VxatPo4Ah2BPJ0=,iv:wO7TZoLHfvka4yk+/YA1UhqCXO6zof95QrWV+mytelU=,tag:CAJsTZ2Kszw2Uy3wlNwHLg==,type:str]
sops:
  age:
    - recipient: age1cttxajn7lhmn2536rtxtdwtjr43t3y6v759xhdaj5hmdge02kp7s80004v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bklGbzBYYnJ0VUZ5Z014
        VW11ckZjTUJiaUZIYWZZUVdVcVpXVDVYdTJNClUyM0pYQml5VnZ5dUlNVkdtWDNs
        am9lSXVlZEFoSkN4b0lwSWVyOGlsUjQKLS0tIDc2NHNzVGNreWsrRmI5bkROalh5
        cktkb0o4S25RMU9UZzBrdjl2ZFBWR1EKdxPDnb3/n6sLVhVcT/acRzfVQF7t/UZp
        qnVfGng4y8pUvlQttpd52oT8WtnYHuoqp4bhI62GPbgIhbo6AaG+vQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T20:55:09Z"
  mac: ENC[AES256_GCM,data:++MF3SdhWjHf/Y3e03qEb38UjlvvIbJgYO56X29MTsuc/tbH4cm7a89Mp73nOl+f7S0iMtQ3gWUWhEDtGSRSn5MRzOWLCvrQLoyj+pUcb1mULacnc+BOt/TtySk9f6Gh+hXgnXYZbD4fM7TYqlmIBgCJkfybm6mkBO2WaC7klbs=,iv:00Xf6DTT9CiQyTcn1l0Und3s5WbNPVS3m4qLDSba908=,tag:S5vqfjECBHmJUUW5Z+J+Wg==,type:str]
  encrypted_regex: ^(secrets)$
  mac_only_encrypted: true
  version: 3.12.1
