---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=konflux-ci/konflux-ci
  - https://github.com/konflux-ci/konflux-ci/releases/download/v0.1.13/install.yaml
